#!/usr/bin/env python3
"""Check the actual generated hosts header against the release version."""
from pathlib import Path
import subprocess
import tempfile

root=Path(__file__).resolve().parents[1]
source=(root/'source/hosts.c').read_text()
body=source[source.index('// Small growable-buffer helper'):source.index('bool hosts_write_all')]
with tempfile.TemporaryDirectory() as directory:
    p=Path(directory)
    c=p/'hosts.c'
    c.write_text('#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <stdarg.h>\n#include "config.h"\n#include "hosts.h"\n#include "version.h"\n'+body+'\nint main(void){char*s=hosts_build(GRID0PLUS_SERVER_IP_DEFAULT);if(!s)return 1;puts(s);free(s);return 0;}\n')
    binary=p/'hosts'
    subprocess.run(['cc','-Wall','-Wextra','-Werror','-I'+str(root/'source'),str(c),'-o',str(binary)],check=True)
    text=subprocess.check_output([str(binary)],text=True)
    version=next(line.split(':=',1)[1].strip() for line in (root/'Makefile').read_text().splitlines() if line.startswith('APP_VERSION :='))
    assert f'# Generated by GRID0+ Toolbox v{version}.' in text
print('PASS: generated hosts header contains the actual release version')
