#include "hosts.h"
#include "config.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <switch.h>

static bool writeTextFile(const char *path, const char *contents) {
    FILE *f = fopen(path, "w");
    if (!f) return false;
    size_t n = strlen(contents);
    bool ok = (fwrite(contents, 1, n, f) == n);
    fclose(f);
    return ok;
}

static bool fileContains(const char *path, const char *needle) {
    FILE *f = fopen(path, "rb");
    if (!f) return false;
    char buf[8192];
    size_t n = fread(buf, 1, sizeof(buf) - 1, f);
    fclose(f);
    buf[n] = '\0';
    return strstr(buf, needle) != NULL;
}

// Small growable-buffer helper for hosts_build(): the file is only ever a few
// KB, but sizing it up-front would mean re-deriving that size by hand every
// time an entry is added.
typedef struct { char *buf; size_t len; size_t cap; } strbuf;

static void sb_init(strbuf *sb) {
    sb->cap = 4096;
    sb->len = 0;
    sb->buf = (char *)malloc(sb->cap);
    if (sb->buf) sb->buf[0] = '\0';
}

static void sb_append(strbuf *sb, const char *s) {
    if (!sb->buf) return;
    size_t sl = strlen(s);
    if (sb->len + sl + 1 > sb->cap) {
        size_t ncap = (sb->len + sl + 1) * 2;
        char *nb = (char *)realloc(sb->buf, ncap);
        if (!nb) { free(sb->buf); sb->buf = NULL; return; }
        sb->buf = nb;
        sb->cap = ncap;
    }
    memcpy(sb->buf + sb->len, s, sl + 1);
    sb->len += sl;
}

static void sb_appendf(strbuf *sb, const char *fmt, ...) {
    char line[256];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(line, sizeof(line), fmt, ap);
    va_end(ap);
    sb_append(sb, line);
}

char *hosts_build(const char *ip) {
    strbuf sb;
    sb_init(&sb);
    if (!sb.buf) return NULL;

    sb_append(&sb, "# ============================================================\n");
    sb_append(&sb, "# " SWITCHNET_HOSTS_HEADER_MARK "\n");
    sb_append(&sb, "# Generated by the SwitchNet Toolbox homebrew. Do not edit by hand:\n");
    sb_append(&sb, "# it will be overwritten the next time SwitchNet mode is applied.\n");
    sb_append(&sb, "# Rule: the LAST matching line wins. '*' = 0+ chars, '%' = lp1.\n");
    sb_append(&sb, "# ============================================================\n\n");

    sb_append(&sb, "# --- Nintendo online endpoints -> SwitchNet ---\n");
    sb_appendf(&sb, "%s    *.nintendo.com\n", ip);
    sb_appendf(&sb, "%s    *.nintendo.co.jp\n", ip);
    sb_appendf(&sb, "%s accounts.nintendo.com\n", ip);
    sb_appendf(&sb, "%s api.accounts.nintendo.com\n", ip);
    sb_appendf(&sb, "%s    *.srv.nintendo.net\n", ip);
    sb_appendf(&sb, "%s    *srv.nintendo.net\n", ip);
    // Covers every game's NEX secure server without hardcoding per-game IDs.
    sb_appendf(&sb, "%s g2*.s.n.srv.nintendo.net\n", ip);

    // These seven are all real, active SwitchNet endpoints (friend
    // recommendations, invitations, NSO membership, eLicense, eShop's
    // pre-account-link host, service status, and the Splatoon 3 lobby host on
    // port 7575) but none of them are on .nintendo.com or .srv.nintendo.net,
    // so none match the wildcards above -- without an explicit line each one
    // falls straight through DNS-MITM to real Nintendo instead of the
    // SwitchNet server that actually answers it. Cross-checked host by host
    // against switchnet's own internal/nintendo/hosts.go, not assumed from
    // the pattern above.
    sb_append(&sb, "\n# --- More SwitchNet endpoints, not on a wildcard above ---\n");
    sb_appendf(&sb, "%s app.lp1.five.nintendo.net\n", ip);
    sb_appendf(&sb, "%s capi.lp1.op2.nintendo.net\n", ip);
    sb_appendf(&sb, "%s dragons.hac.lp1.dragons.nintendo.net\n", ip);
    sb_appendf(&sb, "%s pubkey.lp1.dragons.nintendo.net\n", ip);
    sb_appendf(&sb, "%s beach.hac.lp1.eshop.nintendo.net\n", ip);
    sb_appendf(&sb, "%s service-status-lp1.cdn.nintendo.net\n", ip);
    sb_appendf(&sb, "%s gamesync.npln.nintendo.net\n", ip);

    sb_append(&sb, "\n# --- Telemetry -> null-routed (kept off in both modes) ---\n");
    sb_append(&sb, "0.0.0.0          receive-%.dg.srv.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          receive-%.er.srv.nintendo.net\n");

    // None of the hosts below match the broad *.nintendo.com / *.srv.nintendo.net
    // patterns above (they're on .nintendo.net or .cdn.nintendo.net directly), so
    // without an explicit line here they fall straight through DNS-MITM to real
    // upstream DNS -- reaching real Nintendo, not just "unhandled". Matches
    // switchnet's own internal/nintendo/hosts.go (ServiceBlackhole), the
    // authoritative list this repo's README says to extend from.
    sb_append(&sb, "\n# --- System updates -> null-routed: this emuMMC never talks to\n");
    sb_append(&sb, "# real Nintendo, so passthrough would only leak real update traffic.\n");
    sb_append(&sb, "# NOTE: atumn (system update), not atum (phase-3 game content, listed\n");
    sb_append(&sb, "# separately below) -- one-letter difference, same d4c domain.\n");
    sb_append(&sb, "0.0.0.0          sun.hac.lp1.d4c.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          atumn.hac.lp1.d4c.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          aqua.hac.lp1.d4c.nintendo.net\n");

    // Observed on real hardware reaching a real Nintendo IP when left off this
    // list entirely (switchnet's own 2026-08-26 capture, same failure mode as
    // the d4c hosts above): background content delivery, not needed yet.
    sb_append(&sb, "\n# --- BCAT background content delivery -> null-routed ---\n");
    sb_append(&sb, "0.0.0.0          bcat-list-lp1.cdn.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          bcat-data-lp1.cdn.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          bcat-topics-lp1.cdn.nintendo.net\n");

    // Phase 3 (eShop) hosts, not built on this server -- same reasoning as the
    // d4c/BCAT groups above, so null-routed rather than left to fall through.
    // hac.lp1.savanna.srv.nintendo.net and cdn.accounts.nintendo.com are
    // deliberately NOT listed here: both already match *.srv.nintendo.net /
    // *.nintendo.com above and go to SwitchNet, not real Nintendo.
    sb_append(&sb, "\n# --- eShop (not built) -> null-routed ---\n");
    sb_append(&sb, "0.0.0.0          atum.hac.lp1.d4c.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          bugyo.hac.lp1.eshop.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          tagaya.hac.lp1.eshop.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          ecs-lp1.hac.shop.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          ias-lp1.hac.shop.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          idbe-hac.cdn.nintendo.net\n");

    sb_append(&sb, "\n# --- Browser connectivity check -> SwitchNet ---\n");
    sb_appendf(&sb, "%s conntest.nintendowifi.net\n", ip);
    sb_appendf(&sb, "%s ctest.cdn.nintendo.net\n", ip);

    sb_append(&sb, "\n# --- Add SwitchNet-specific hostnames below as needed. ---\n");

    return sb.buf;
}

bool hosts_write_all(const char *ip) {
    if (!switchnet_ensure_dir(SWITCHNET_HOSTS_DIR)) return false;
    char *content = hosts_build(ip);
    if (!content) return false;
    bool a = writeTextFile(SWITCHNET_HOSTS_SYSMMC, content);
    bool b = writeTextFile(SWITCHNET_HOSTS_EMUMMC, content);
    free(content);
    return a && b;
}

void hosts_clear_own(void) {
    if (fileContains(SWITCHNET_HOSTS_SYSMMC, SWITCHNET_HOSTS_HEADER_MARK))
        remove(SWITCHNET_HOSTS_SYSMMC);
    if (fileContains(SWITCHNET_HOSTS_EMUMMC, SWITCHNET_HOSTS_HEADER_MARK))
        remove(SWITCHNET_HOSTS_EMUMMC);
}

bool hosts_is_switchnet_active(void) {
    return fileContains(SWITCHNET_HOSTS_SYSMMC, SWITCHNET_HOSTS_HEADER_MARK) ||
           fileContains(SWITCHNET_HOSTS_EMUMMC, SWITCHNET_HOSTS_HEADER_MARK);
}

// Rewrites system_settings.ini line by line, preserving every key/section
// except enable_dns_mitm / add_defaults_to_dns_hosts under [atmosphere], which
// are set (or appended, if missing) to the requested values.
bool hosts_set_dns_mitm(bool enable, bool addDefaults) {
    static const char *K1 = "enable_dns_mitm";
    static const char *K2 = "add_defaults_to_dns_hosts";
    const char *V1 = enable ? "enable_dns_mitm = u8!0x1\n" : "enable_dns_mitm = u8!0x0\n";
    const char *V2 = addDefaults ? "add_defaults_to_dns_hosts = u8!0x1\n" : "add_defaults_to_dns_hosts = u8!0x0\n";

    switchnet_ensure_dir("sdmc:/atmosphere/config");

    char *buf = NULL;
    long sz = 0;
    FILE *f = fopen(SWITCHNET_SETTINGS_INI, "rb");
    if (f) {
        fseek(f, 0, SEEK_END);
        sz = ftell(f);
        fseek(f, 0, SEEK_SET);
        buf = (char *)malloc((size_t)sz + 1);
        if (!buf) { fclose(f); return false; }
        if (sz > 0) {
            size_t nr = fread(buf, 1, (size_t)sz, f);
            if (nr != (size_t)sz) { free(buf); buf = NULL; sz = 0; }
        }
        if (buf) buf[sz] = '\0';
        fclose(f);
    }

    strbuf out;
    sb_init(&out);
    if (!out.buf) { free(buf); return false; }

    bool inAtmos = false, sawAtmos = false, setK1 = false, setK2 = false;
    char *line = buf;
    while (line && *line) {
        char *nl = strchr(line, '\n');
        size_t llen = nl ? (size_t)(nl - line + 1) : strlen(line);
        char saved = line[llen];
        line[llen] = '\0';

        char *t = line;
        while (*t == ' ' || *t == '\t') t++;

        if (*t == '[') {
            if (inAtmos) {
                if (!setK1) { sb_append(&out, V1); setK1 = true; }
                if (!setK2) { sb_append(&out, V2); setK2 = true; }
            }
            inAtmos = (strncmp(t, "[atmosphere]", 12) == 0);
            if (inAtmos) sawAtmos = true;
            sb_append(&out, line);
        } else if (inAtmos) {
            char *k = t;
            if (*k == ';' || *k == '#') { k++; while (*k == ' ' || *k == '\t') k++; }
            if (strncmp(k, K1, strlen(K1)) == 0) { sb_append(&out, V1); setK1 = true; }
            else if (strncmp(k, K2, strlen(K2)) == 0) { sb_append(&out, V2); setK2 = true; }
            else sb_append(&out, line);
        } else {
            sb_append(&out, line);
        }

        line[llen] = saved;
        line = nl ? nl + 1 : NULL;
    }
    free(buf);

    if (inAtmos) {
        if (out.len > 0 && out.buf[out.len - 1] != '\n') sb_append(&out, "\n");
        if (!setK1) sb_append(&out, V1);
        if (!setK2) sb_append(&out, V2);
    }
    if (!sawAtmos) {
        if (out.len > 0 && out.buf[out.len - 1] != '\n') sb_append(&out, "\n");
        sb_append(&out, "[atmosphere]\n");
        sb_append(&out, V1);
        sb_append(&out, V2);
    }

    if (!out.buf) return false;
    bool ok = writeTextFile(SWITCHNET_SETTINGS_INI, out.buf);
    free(out.buf);
    return ok;
}

// Same rewrite-preserving-everything-else shape as hosts_set_dns_mitm above,
// for exosphere.ini's single blank_prodinfo_emummc key under [exosphere]
// instead of system_settings.ini's two atmosphere keys.
bool hosts_set_blank_prodinfo_emummc(bool blank) {
    static const char *K = "blank_prodinfo_emummc";
    const char *V = blank ? "blank_prodinfo_emummc=1\n" : "blank_prodinfo_emummc=0\n";

    char *buf = NULL;
    long sz = 0;
    FILE *f = fopen(SWITCHNET_EXOSPHERE_INI, "rb");
    if (f) {
        fseek(f, 0, SEEK_END);
        sz = ftell(f);
        fseek(f, 0, SEEK_SET);
        buf = (char *)malloc((size_t)sz + 1);
        if (!buf) { fclose(f); return false; }
        if (sz > 0) {
            size_t nr = fread(buf, 1, (size_t)sz, f);
            if (nr != (size_t)sz) { free(buf); buf = NULL; sz = 0; }
        }
        if (buf) buf[sz] = '\0';
        fclose(f);
    }

    strbuf out;
    sb_init(&out);
    if (!out.buf) { free(buf); return false; }

    bool inExo = false, sawExo = false, setK = false;
    char *line = buf;
    while (line && *line) {
        char *nl = strchr(line, '\n');
        size_t llen = nl ? (size_t)(nl - line + 1) : strlen(line);
        char saved = line[llen];
        line[llen] = '\0';

        char *t = line;
        while (*t == ' ' || *t == '\t') t++;

        if (*t == '[') {
            if (inExo && !setK) { sb_append(&out, V); setK = true; }
            inExo = (strncmp(t, "[exosphere]", 11) == 0);
            if (inExo) sawExo = true;
            sb_append(&out, line);
        } else if (inExo) {
            char *k = t;
            if (*k == ';' || *k == '#') { k++; while (*k == ' ' || *k == '\t') k++; }
            if (strncmp(k, K, strlen(K)) == 0) { sb_append(&out, V); setK = true; }
            else sb_append(&out, line);
        } else {
            sb_append(&out, line);
        }

        line[llen] = saved;
        line = nl ? nl + 1 : NULL;
    }
    free(buf);

    if (inExo && !setK) {
        if (out.len > 0 && out.buf[out.len - 1] != '\n') sb_append(&out, "\n");
        sb_append(&out, V);
    }
    if (!sawExo) {
        if (out.len > 0 && out.buf[out.len - 1] != '\n') sb_append(&out, "\n");
        sb_append(&out, "[exosphere]\n");
        sb_append(&out, V);
    }

    if (!out.buf) return false;
    bool ok = writeTextFile(SWITCHNET_EXOSPHERE_INI, out.buf);
    free(out.buf);
    return ok;
}
