#include "hosts.h"
#include "config.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <switch.h>

static bool writeTextFile(const char *path, const char *contents) {
    FILE *f = fopen(path, "w");
    if (!f) return false;
    size_t n = strlen(contents);
    bool ok = (fwrite(contents, 1, n, f) == n);
    fclose(f);
    return ok;
}

static bool fileContains(const char *path, const char *needle) {
    FILE *f = fopen(path, "rb");
    if (!f) return false;
    char buf[8192];
    size_t n = fread(buf, 1, sizeof(buf) - 1, f);
    fclose(f);
    buf[n] = '\0';
    return strstr(buf, needle) != NULL;
}

// Small growable-buffer helper for hosts_build(): the file is only ever a few
// KB, but sizing it up-front would mean re-deriving that size by hand every
// time an entry is added.
typedef struct { char *buf; size_t len; size_t cap; } strbuf;

static void sb_init(strbuf *sb) {
    sb->cap = 4096;
    sb->len = 0;
    sb->buf = (char *)malloc(sb->cap);
    if (sb->buf) sb->buf[0] = '\0';
}

static void sb_append(strbuf *sb, const char *s) {
    if (!sb->buf) return;
    size_t sl = strlen(s);
    if (sb->len + sl + 1 > sb->cap) {
        size_t ncap = (sb->len + sl + 1) * 2;
        char *nb = (char *)realloc(sb->buf, ncap);
        if (!nb) { free(sb->buf); sb->buf = NULL; return; }
        sb->buf = nb;
        sb->cap = ncap;
    }
    memcpy(sb->buf + sb->len, s, sl + 1);
    sb->len += sl;
}

static void sb_appendf(strbuf *sb, const char *fmt, ...) {
    char line[256];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(line, sizeof(line), fmt, ap);
    va_end(ap);
    sb_append(sb, line);
}

char *hosts_build(const char *ip) {
    strbuf sb;
    sb_init(&sb);
    if (!sb.buf) return NULL;

    sb_append(&sb, "# ============================================================\n");
    sb_append(&sb, "# " SWITCHNET_HOSTS_HEADER_MARK "\n");
    sb_append(&sb, "# Generated by the SwitchNet Toolbox homebrew. Do not edit by hand:\n");
    sb_append(&sb, "# it will be overwritten the next time SwitchNet mode is applied.\n");
    sb_append(&sb, "# Rule: the LAST matching line wins. '*' = 0+ chars, '%' = lp1.\n");
    sb_append(&sb, "# ============================================================\n\n");

    sb_append(&sb, "# --- Nintendo online endpoints -> SwitchNet ---\n");
    sb_appendf(&sb, "%s    *.nintendo.com\n", ip);
    sb_appendf(&sb, "%s    *.nintendo.co.jp\n", ip);
    sb_appendf(&sb, "%s accounts.nintendo.com\n", ip);
    sb_appendf(&sb, "%s api.accounts.nintendo.com\n", ip);
    sb_appendf(&sb, "%s    *.srv.nintendo.net\n", ip);
    sb_appendf(&sb, "%s    *srv.nintendo.net\n", ip);
    // Covers every game's NEX secure server without hardcoding per-game IDs.
    sb_appendf(&sb, "%s g2*.s.n.srv.nintendo.net\n", ip);

    sb_append(&sb, "\n# --- Telemetry -> null-routed (kept off in both modes) ---\n");
    sb_append(&sb, "0.0.0.0          receive-%.dg.srv.nintendo.net\n");
    sb_append(&sb, "0.0.0.0          receive-%.er.srv.nintendo.net\n");

    sb_append(&sb, "\n# --- Browser connectivity check -> SwitchNet ---\n");
    sb_appendf(&sb, "%s conntest.nintendowifi.net\n", ip);
    sb_appendf(&sb, "%s ctest.cdn.nintendo.net\n", ip);

    sb_append(&sb, "\n# --- Add SwitchNet-specific hostnames below as needed. ---\n");

    return sb.buf;
}

bool hosts_write_all(const char *ip) {
    if (!switchnet_ensure_dir(SWITCHNET_HOSTS_DIR)) return false;
    char *content = hosts_build(ip);
    if (!content) return false;
    bool a = writeTextFile(SWITCHNET_HOSTS_SYSMMC, content);
    bool b = writeTextFile(SWITCHNET_HOSTS_EMUMMC, content);
    free(content);
    return a && b;
}

void hosts_clear_own(void) {
    if (fileContains(SWITCHNET_HOSTS_SYSMMC, SWITCHNET_HOSTS_HEADER_MARK))
        remove(SWITCHNET_HOSTS_SYSMMC);
    if (fileContains(SWITCHNET_HOSTS_EMUMMC, SWITCHNET_HOSTS_HEADER_MARK))
        remove(SWITCHNET_HOSTS_EMUMMC);
}

bool hosts_is_switchnet_active(void) {
    return fileContains(SWITCHNET_HOSTS_SYSMMC, SWITCHNET_HOSTS_HEADER_MARK) ||
           fileContains(SWITCHNET_HOSTS_EMUMMC, SWITCHNET_HOSTS_HEADER_MARK);
}

// Rewrites system_settings.ini line by line, preserving every key/section
// except enable_dns_mitm / add_defaults_to_dns_hosts under [atmosphere], which
// are set (or appended, if missing) to the requested values.
bool hosts_set_dns_mitm(bool enable, bool addDefaults) {
    static const char *K1 = "enable_dns_mitm";
    static const char *K2 = "add_defaults_to_dns_hosts";
    const char *V1 = enable ? "enable_dns_mitm = u8!0x1\n" : "enable_dns_mitm = u8!0x0\n";
    const char *V2 = addDefaults ? "add_defaults_to_dns_hosts = u8!0x1\n" : "add_defaults_to_dns_hosts = u8!0x0\n";

    switchnet_ensure_dir("sdmc:/atmosphere/config");

    char *buf = NULL;
    long sz = 0;
    FILE *f = fopen(SWITCHNET_SETTINGS_INI, "rb");
    if (f) {
        fseek(f, 0, SEEK_END);
        sz = ftell(f);
        fseek(f, 0, SEEK_SET);
        buf = (char *)malloc((size_t)sz + 1);
        if (!buf) { fclose(f); return false; }
        if (sz > 0) {
            size_t nr = fread(buf, 1, (size_t)sz, f);
            if (nr != (size_t)sz) { free(buf); buf = NULL; sz = 0; }
        }
        if (buf) buf[sz] = '\0';
        fclose(f);
    }

    strbuf out;
    sb_init(&out);
    if (!out.buf) { free(buf); return false; }

    bool inAtmos = false, sawAtmos = false, setK1 = false, setK2 = false;
    char *line = buf;
    while (line && *line) {
        char *nl = strchr(line, '\n');
        size_t llen = nl ? (size_t)(nl - line + 1) : strlen(line);
        char saved = line[llen];
        line[llen] = '\0';

        char *t = line;
        while (*t == ' ' || *t == '\t') t++;

        if (*t == '[') {
            if (inAtmos) {
                if (!setK1) { sb_append(&out, V1); setK1 = true; }
                if (!setK2) { sb_append(&out, V2); setK2 = true; }
            }
            inAtmos = (strncmp(t, "[atmosphere]", 12) == 0);
            if (inAtmos) sawAtmos = true;
            sb_append(&out, line);
        } else if (inAtmos) {
            char *k = t;
            if (*k == ';' || *k == '#') { k++; while (*k == ' ' || *k == '\t') k++; }
            if (strncmp(k, K1, strlen(K1)) == 0) { sb_append(&out, V1); setK1 = true; }
            else if (strncmp(k, K2, strlen(K2)) == 0) { sb_append(&out, V2); setK2 = true; }
            else sb_append(&out, line);
        } else {
            sb_append(&out, line);
        }

        line[llen] = saved;
        line = nl ? nl + 1 : NULL;
    }
    free(buf);

    if (inAtmos) {
        if (out.len > 0 && out.buf[out.len - 1] != '\n') sb_append(&out, "\n");
        if (!setK1) sb_append(&out, V1);
        if (!setK2) sb_append(&out, V2);
    }
    if (!sawAtmos) {
        if (out.len > 0 && out.buf[out.len - 1] != '\n') sb_append(&out, "\n");
        sb_append(&out, "[atmosphere]\n");
        sb_append(&out, V1);
        sb_append(&out, V2);
    }

    if (!out.buf) return false;
    bool ok = writeTextFile(SWITCHNET_SETTINGS_INI, out.buf);
    free(out.buf);
    return ok;
}
